name: Move Issue to In Progress on Branch Creation

on:
  create: # 모든 브랜치가 생성될 때 트리거

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to In Progress
        uses: actions/add-to-project@v0.3.0
        with:
          project_url: https://github.com/orgs/prgrms-web-devcourse-final-project/projects/42
          column_name: In Progress # In Progress 열로 이동
          github_token: ${{ secrets.GITHUB_TOKEN }}
